name: Super Init Demo

on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - xcode: 11.7
            ios: 13.7
          - xcode: 12.2
            ios: 14.2
    
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build for testing
        run: xcodebuild build-for-testing -scheme GitHub-Actions-Demo -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'
      - name: Tests
        run: xcodebuild test-without-building -scheme GitHub-Actions-Demo  -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'
  deploy:
    runs-on: self-hosted-m1
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2
      - name: Archive
        run: xcodebuild -scheme GitHub-Actions-Demo clean archive -configuration release -sdk iphoneos -archivePath GitHub-Actions-Demo.xcarchive
      - name: Sign and export
        run: xcodebuild -exportArchive -archivePath  GitHub-Actions-Demo.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath  build
      - name: Deploy to AppCenter
        run: appcenter distribute release -f build/GitHub-Actions-Demo.ipa -g Collaborators --app roger.tan-kinandcarta.com/GitHub-Actions-Demo --token ${{ secrets.APPCENTER_ACCESS_TOKEN }}
